# Voornaam: Stijn
# Achternaam: Barendse
# Studentnummer: 591527

services:
  db:
    image: mariadb:11
    container_name: mijn-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootwachtwoord
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wpwachtwoord
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mijn-netwerk

  web:
    image: wordpress:latest
    container_name: mijn-web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpwachtwoord
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - mijn-netwerk

volumes:
  db_data:
  wp_data:

networks:
  mijn-netwerk:
    driver: bridge